#!/usr/bin/env python3
"""Generate single_include/fcl_distance.hpp from include/fcl/** headers.

Performs a topological expansion of the include graph starting from
fcl/fcl.h: every internal include ("fcl/...") is inlined exactly once, in
dependency order; system includes are collected and emitted once at the top.
Include guards of individual files become redundant but are kept out of the
output (guard lines and their #endif are stripped structurally by relying on
the once-only inlining).
"""
import os
import re
import sys
from datetime import date

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
INC = os.path.join(ROOT, "include")
ENTRY = "fcl/fcl.h"
OUT = os.path.join(ROOT, "single_include", "fcl_distance.hpp")

inc_re = re.compile(r'^\s*#\s*include\s+([<"])([^">]+)[">]')

emitted = set()
system_includes = []
system_seen = set()
body_lines = []


def strip_own_guard(lines, rel):
    """Remove the outermost include guard (#ifndef/#define pair + final #endif)."""
    # find first #ifndef and matching #define
    n = len(lines)
    i = 0
    guard = None
    while i < n:
        s = lines[i].strip()
        if s.startswith("#ifndef"):
            parts = s.split()
            if len(parts) >= 2 and i + 1 < n:
                nxt = lines[i + 1].strip().split()
                if len(nxt) >= 2 and nxt[0] == "#define" and nxt[1] == parts[1]:
                    guard = (i, parts[1])
            break
        if s and not s.startswith("//") and not s.startswith("/*") \
           and not s.startswith("*") and not s.startswith("*/"):
            break
        i += 1
    if guard is None:
        return lines
    gi, gname = guard
    # find the last #endif in the file
    last_endif = None
    for j in range(n - 1, -1, -1):
        if lines[j].strip().startswith("#endif"):
            last_endif = j
            break
    if last_endif is None or last_endif <= gi + 1:
        return lines
    out = lines[:gi] + lines[gi + 2:last_endif] + lines[last_endif + 1:]
    return out


def inline_file(rel):
    rel = rel.replace("\\", "/")
    if rel in emitted:
        return
    emitted.add(rel)
    path = os.path.join(INC, rel.replace("/", os.sep))
    if not os.path.isfile(path):
        raise SystemExit("missing internal header: " + rel)
    with open(path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()
    lines = strip_own_guard(lines, rel)
    body_lines.append("")
    body_lines.append("//" + "=" * 76)
    body_lines.append("// BEGIN %s" % rel)
    body_lines.append("//" + "=" * 76)
    # FCL_HAVE_OCTOMAP is 0 in this extraction, so includes guarded by it are
    # emitted verbatim rather than inlined (the octree headers are not shipped).
    octomap_depth = 0
    for line in lines:
        s = line.strip()
        if octomap_depth:
            if s.startswith("#if"):
                octomap_depth += 1
            elif s.startswith("#endif"):
                octomap_depth -= 1
            body_lines.append(line)
            continue
        if re.match(r'^\s*#\s*if\s+FCL_HAVE_OCTOMAP\b', line):
            octomap_depth = 1
            body_lines.append(line)
            continue
        m = inc_re.match(line)
        if m:
            kind, target = m.group(1), m.group(2)
            if target.startswith("fcl/"):
                inline_file(target)
                continue
            if kind == "<":
                if target not in system_seen:
                    system_seen.add(target)
                    system_includes.append(target)
                continue
            # quoted non-fcl include: treat as system-ish (should not happen)
            if target not in system_seen:
                system_seen.add(target)
                system_includes.append(target)
            continue
        body_lines.append(line)
    body_lines.append("// END %s" % rel)


def main():
    inline_file(ENTRY)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// fcl_distance.hpp — single-header amalgamation of the\n")
        f.write("// fcl_distance library: a header-only extraction of the\n")
        f.write("// fcl::distance reference closure from FCL 0.7.0\n")
        f.write("// (https://github.com/flexible-collision-library/fcl,\n")
        f.write("// BSD-3-Clause).  Every fcl/** header is inlined here; the\n")
        f.write("// external dependencies are unchanged from upstream FCL:\n")
        f.write("//   - Eigen 3   (headers only)\n")
        f.write("//   - libccd    (link with -lccd)\n")
        f.write("// Generated by tools/amalgamate.py on %s — do not edit.\n"
                % date.today().isoformat())
        f.write("//\n")
        f.write("// Usage: #include \"fcl_distance.hpp\"\n\n")
        f.write("#ifndef FCL_DISTANCE_SINGLE_HEADER_HPP\n")
        f.write("#define FCL_DISTANCE_SINGLE_HEADER_HPP\n\n")
        for h in system_includes:
            f.write("#include <%s>\n" % h)
        f.write("\n")
        for line in body_lines:
            f.write(line + "\n")
        f.write("\n#endif // FCL_DISTANCE_SINGLE_HEADER_HPP\n")
    print("wrote %s (%d headers inlined, %d system includes)"
          % (OUT, len(emitted), len(system_includes)))


if __name__ == "__main__":
    main()
